set(_q "")
if(${CMAKE_FIND_PACKAGE_NAME}_FIND_QUIETLY)
    set(_q QUIET)
    set(_quietly TRUE)
endif()
find_package(${CMAKE_FIND_PACKAGE_NAME} ${${CMAKE_FIND_PACKAGE_NAME}_FIND_VERSION} CONFIG ${_q})

if (NOT ${CMAKE_FIND_PACKAGE_NAME}_FOUND)
    # Fall-back solution to find the Cereal serialization library header file
    include(CheckIncludeFileCXX)
    add_library(cereal INTERFACE)
    # Use absolute path to deps include directory, with fallback to relative path
    set(_cereal_found FALSE)
    if(DEFINED CMAKE_PREFIX_PATH)
        foreach(_prefix ${CMAKE_PREFIX_PATH})
            if(EXISTS "${_prefix}/include/cereal")
                target_include_directories(cereal INTERFACE "${_prefix}/include")
                set(_cereal_found TRUE)
                break()
            endif()
        endforeach()
    endif()
    if(NOT _cereal_found)
        target_include_directories(cereal INTERFACE include)
    endif()

    if (_quietly)
        set(CMAKE_REQUIRED_QUIET ON)
    endif()
    CHECK_INCLUDE_FILE_CXX("cereal/cereal.hpp" HAVE_CEREAL_H)

    if (NOT HAVE_CEREAL_H)
        if (${CMAKE_FIND_PACKAGE_NAME}_FIND_REQUIRED)
            message(FATAL_ERROR "Cereal library not found. Please install the dependency.")
        elseif(NOT _quietly)
            message(WARNING "Cereal library not found.")
        endif()
    endif ()
endif()
